### ISSUE TITLE
Free Quality Images

### ISSUE THREAD

**Issue by Madchatthew** [vlipatdev/frontend-resources#1]
Can a section on where to use quality images that are free to use on whatever kind of website? I know that Colt mentions a free one and I have seen a couple others but can't for the life of me remember which ones they are.

**Comment by Madchatthew** [comment]
I created a PR request with a couple of free image sites.

**Comment by vlipatdev** [comment]
Hey thanks for the recommendation. Your pull request was successfully merged.
